### ISSUE TITLE
Segfault in release mode

### ISSUE THREAD

**Issue by drug007** [ariovistus/multi_index#2]
```
void test()
{
    import multi_index;

    alias Id = uint;
    alias Timestamp = long;

    static struct Item
    {
        Id id;
        Timestamp time;

        int opCmp(ref const(Item) item) const
        {
            if(this.time < item.time)
                return -1;
            if(this.time > item.time)
                return 1;
            return 0;
        }
    }

    alias Container = MultiIndexContainer!(Item, IndexedBy!(
        OrderedNonUnique!("a.id"),   "byId", 
        OrderedNonUnique!("a.time"), "byTime"));

    Container c = new Container();
    c.byId.insert([
        Item(95, 100), 
        Item(11, 10), 
        Item(45, 20), 
        Item( 2, 15), 
        Item( 1, 15),
        Item(22, 45), 
        Item(22, 35), // The second instance of the same id with different time
        ]);
}
```

runs in debug mode and fails in release mode using dmd2-067, amd64, linux both 1.0.1 version of library and master too

**Comment by drug007** [comment]
Probably I was hurry, release mode fails using dmd, but works fine using ldc...

**Comment by ariovistus** [comment]
pretty sure ldc isn't at 2.067 front end.. (not seeing this in dmd2.066)

**Comment by drug007** [comment]
this code fails in dmd both 2.066 and 2.067 at my box, but works as expected with ldc 2.066 & 2.067 (there is branch merge-2.067, not release of course)

**Comment by ariovistus** [comment]
I think I was just using dub incorrectly, can reproduce with dmd 2.067 with -release -O, not with -release only, don't think I tested with -O only. wanna say this is a compiler bug.

**Comment by drug007** [comment]
I thinks you're right, it's a compiler bug. What would be better - submit this bug `as is` now, or try to reduce it before but submit it later, may be much later and I'm not sure I can manage it at all?

**Comment by ariovistus** [comment]
It's more likely to be fixed with a reduced case. I'll try and whittle it down this weekend.

**Comment by ariovistus** [comment]
nevermind, I got it tonight:

https://issues.dlang.org/show_bug.cgi?id=14453

**Comment by drug007** [comment]
Thank you!

**Comment by ariovistus** [comment]
might as well leave this opened unti it has been resolved in dmd.

**Comment by drug007** [comment]
I see.

**Comment by drug007** [comment]
Can not reproduce it using `dmd 2.076`. Could you confirm this and close the issue in this case?

**Comment by ariovistus** [comment]
Agreed. 1.0.1 does not compile with 2.076. 1.1.1 does and does not segfault. 1.1.1 also compiles without segfault on 2.067, so the issue was likely a bug in this library.
